// web/src/components/Button.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLButtonAttributes } from 'svelte/elements'

  type Props = {
    variant?: 'default' | 'success' | 'destructive' | 'outline' | 'secondary' | 'tertiary' | 'muted' | 'ghost' | 'link'
    size?: 'xs' | 'default' | 'sm' | 'lg' | 'xl' | 'icon' | 'icon-md' | 'icon-sm' | 'icon-only'
    class?: string
    children: Snippet
  } & HTMLButtonAttributes

  let {
    variant = 'default',
    size = 'default',
    class: className = '',
    children,
    ...restProps
  }: Props = $props()
</script>

<button
  class="btn btn-{variant} btn-{size} {className}"
  {...restProps}
>
  {@render children()}
</button>

<style>
  .btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
    white-space: nowrap;
    font-size: 14px;
    font-weight: 500;
    line-height: 1;
    border: 1px solid transparent;
    cursor: pointer;
    user-select: none;
    flex-shrink: 0;
    transition: all 0.15s ease;
    outline: none;
    font-family: inherit;
  }

  .btn:focus-visible {
    box-shadow: 0 0 0 2px var(--background), 0 0 0 4px var(--ring);
  }

  .btn:disabled {
    pointer-events: none;
    opacity: 0.5;
  }

  .btn:disabled:where(.btn-default, .btn-success, .btn-destructive) {
    box-shadow: none;
  }

  :global(svg) {
    pointer-events: none;
    flex-shrink: 0;
  }

  /* Variants */
  .btn-default {
    background: var(--primary);
    color: var(--primary-foreground);
    border-color: transparent;
  }
  .btn-default:hover:not(:disabled) {
    opacity: 0.9;
  }

  .btn-success {
    background: #10b981;
    color: white;
    border-color: transparent;
  }
  .btn-success:hover:not(:disabled) {
    opacity: 0.9;
  }

  .btn-destructive {
    background: var(--destructive, #ef4444);
    color: white;
    border-color: transparent;
  }
  .btn-destructive:hover:not(:disabled) {
    opacity: 0.9;
  }

  .btn-outline {
    background: var(--background);
    color: var(--foreground);
    border-color: var(--border);
    box-shadow: 0 1px 2px rgb(0 0 0 / 0.05);
  }
  .btn-outline:hover:not(:disabled) {
    background: var(--secondary);
    color: var(--accent-foreground, var(--foreground));
  }

  .btn-secondary {
    background: var(--secondary);
    color: var(--secondary-foreground);
    border-color: transparent;
  }
  .btn-secondary:hover:not(:disabled) {
    opacity: 0.8;
  }

  .btn-tertiary {
    background: rgb(23 23 23 / 0.1);
    color: var(--foreground);
    border-color: transparent;
    box-shadow: none;
  }

  .btn-muted {
    background: var(--secondary);
    color: color-mix(in srgb, var(--accent-foreground, var(--foreground)) 75%, transparent);
    border-color: transparent;
  }
  .btn-muted:hover:not(:disabled) {
    color: var(--accent-foreground, var(--foreground));
  }

  .btn-ghost {
    background: transparent;
    color: var(--foreground);
    border-color: transparent;
  }
  .btn-ghost:hover:not(:disabled) {
    background: var(--accent);
    color: var(--accent-foreground, var(--foreground));
  }
  :global(.dark) .btn-ghost:hover:not(:disabled) {
    background: color-mix(in srgb, var(--accent) 50%, transparent);
  }

  .btn-link {
    background: transparent;
    color: var(--primary);
    border-color: transparent;
    text-decoration: none;
    text-underline-offset: 4px;
  }
  .btn-link:hover:not(:disabled) {
    text-decoration: underline;
  }

  /* Sizes */
  .btn-xs {
    height: 22px;
    padding: 0 6px;
    font-size: 12px;
    border-radius: 4px;
    gap: 6px;
  }

  .btn-default:where(.btn) {
    height: 36px;
    padding: 0 14px 0 14px;
    border-radius: 8px;
  }

  .btn-sm {
    height: 32px;
    padding: 0 12px;
    font-size: 13px;
    border-radius: 6px;
    gap: 6px;
  }

  .btn-lg {
    height: 40px;
    padding: 0 24px;
    font-size: 14px;
    border-radius: 6px;
  }

  .btn-xl {
    height: 44px;
    padding: 0 28px;
    font-size: 14px;
    border-radius: 6px;
  }

  .btn-icon {
    width: 36px;
    height: 36px;
    padding: 0;
    border-radius: 8px;
  }

  .btn-icon-md {
    width: 32px;
    height: 32px;
    padding: 0;
    border-radius: 6px;
  }

  .btn-icon-sm {
    width: 20px;
    height: 20px;
    padding: 0;
    border-radius: 4px;
  }

  .btn-icon-only {
    width: 16px;
    height: 16px;
    padding: 0;
    border-radius: 0;
  }
</style>

// web/src/diffshub/components/Button.tsx
import { Slot } from '@radix-ui/react-slot';
import { cva, type VariantProps } from 'class-variance-authority';
import * as React from 'react';

import { cn } from '@/lib/cn';

const buttonVariants = cva(
  'inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none flex-shrink-0 [&_svg]:shrink-0 outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive cursor-pointer select-none',
  {
    variants: {
      variant: {
        default: 'bg-primary text-primary-foreground hover:bg-primary/90',
        success:
          'bg-teal-500 text-white hover:bg-teal-500/90 focus-visible:ring-teal-500/20 dark:focus-visible:ring-green-500/40 dark:bg-green-500/60',
        destructive:
          'bg-destructive text-white hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60',
        outline:
          'border bg-background hover:bg-secondary hover:text-accent-foreground dark:hover:bg-input/50 dark:border-neutral-800',
        secondary:
          'bg-secondary text-secondary-foreground hover:bg-secondary/80',
        tertiary: 'bg-neutral-900/10',
        muted:
          'bg-secondary text-accent-foreground/75 hover:text-accent-foreground',
        ghost:
          'border bg-transparent border-transparent hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50',
        link: 'text-primary underline-offset-4 hover:underline',
      },
      size: {
        xs: 'h-5.5 rounded-sm gap-1.5 px-1.5 text-xs',
        default: 'h-9 px-3.5 py-2 rounded-lg',
        sm: 'h-8 rounded-md gap-1.5 px-3',
        lg: 'h-10 rounded-md px-6',
        xl: 'h-11 rounded-md px-7',
        icon: 'size-9',
        'icon-md': 'size-8 rounded-md',
        'icon-sm': 'size-5 rounded-sm',
        'icon-only': 'size-4 rounded-0 p-0',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'default',
    },
  }
);

export type ButtonProps = React.ComponentProps<'button'> &
  VariantProps<typeof buttonVariants> & {
    asChild?: boolean;
  };

function Button({
  className,
  variant,
  size,
  asChild = false,
  ...props
}: ButtonProps) {
  const Comp = asChild ? Slot : 'button';

  return (
    <Comp
      data-slot="button"
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  );
}

export { Button, buttonVariants };
