// web/src/components/Input.svelte
<script lang="ts">
  interface Props {
    size?: 'default' | 'lg' | 'sm'
    type?: string
    placeholder?: string
    value?: string
    disabled?: boolean
    class?: string
    spellcheck?: boolean
    'aria-label'?: string
    oninput?: (e: Event) => void
    onkeydown?: (e: KeyboardEvent) => void
  }

  let {
    size = 'default',
    type = 'text',
    placeholder,
    value = $bindable(''),
    disabled = false,
    class: className = '',
    spellcheck,
    'aria-label': ariaLabel,
    oninput,
    onkeydown,
  }: Props = $props()
</script>

<input
  {type}
  {placeholder}
  {disabled}
  {spellcheck}
  aria-label={ariaLabel}
  class="input input-{size} {className}"
  bind:value={value}
  oninput={oninput}
  onkeydown={onkeydown}
/>

<style>
  .input {
    width: 100%;
    min-width: 0;
    border: 1px solid var(--border);
    background: transparent;
    color: var(--foreground);
    font-family: inherit;
    outline: none;
    transition: color 0.15s ease, box-shadow 0.15s ease;
    box-shadow: 0 1px 2px rgb(0 0 0 / 0.05);
  }

  :global(.dark) .input {
    background: color-mix(in srgb, var(--input) 30%, transparent);
  }

  .input::placeholder {
    color: var(--muted-foreground);
  }

  .input::selection {
    background: var(--primary);
    color: var(--primary-foreground);
  }

  .input:focus-visible {
    border-color: var(--ring);
    box-shadow: 0 0 0 2px var(--background), 0 0 0 4px var(--ring);
  }

  .input:disabled {
    pointer-events: none;
    opacity: 0.5;
    cursor: not-allowed;
  }

  .input-default {
    height: 36px;
    padding: 0 12px;
    font-size: 14px;
    border-radius: 6px;
  }

  .input-lg {
    height: 40px;
    padding: 0 16px;
    font-size: 14px;
    border-radius: 6px;
  }

  .input-sm {
    height: 32px;
    padding: 0 8px;
    font-size: 12px;
    border-radius: 6px;
  }
</style>

// web/src/diffshub/components/Input.tsx
import { cva, type VariantProps } from 'class-variance-authority';
import * as React from 'react';

import { cn } from '@/lib/cn';

// Sizes are kept in lockstep with `Button` so an Input + Button paired in the
// same row line up at the same height/radius/padding rhythm.
const inputVariants = cva(
  'file:text-foreground placeholder:text-muted-foreground selection:bg-primary selection:text-primary-foreground dark:bg-input/30 border-input w-full min-w-0 border bg-transparent shadow-xs transition-[color,box-shadow] outline-none file:inline-flex file:border-0 file:bg-transparent file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive',
  {
    variants: {
      inputSize: {
        default:
          'h-9 rounded-md px-3 py-1 text-base file:h-7 file:text-sm md:text-sm',
        lg: 'h-10 rounded-md px-4 text-base file:h-8 file:text-sm',
        sm: 'h-8 rounded-md px-2 py-1 text-xs',
      },
    },
    defaultVariants: {
      inputSize: 'default',
    },
  }
);

// `inputSize` is used instead of `size` because `size` is a native HTML input
// attribute (character-width hint) and we don't want our variant prop to
// shadow it.
export type InputProps = Omit<React.ComponentProps<'input'>, 'size'> &
  VariantProps<typeof inputVariants>;

function Input({ className, type, inputSize, ...props }: InputProps) {
  return (
    <input
      type={type}
      data-slot="input"
      className={cn(inputVariants({ inputSize, className }))}
      {...props}
    />
  );
}

export { Input, inputVariants };
